// quizz-web-app/react-quizz-web-app/src/routes/auth/Register.jsx
import React from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../../context/AuthContext.jsx";
import { flash } from "react-universal-flash";

function Register() {
    const navigate = useNavigate();
    const authContext = useAuth();

    const handleSubmit = async e => {
        e.preventDefault();
        const data = new FormData(e.target);
        const firstName = data.get("firstName");
        const lastName = data.get("lastName");
        const email = data.get("email");
        const password = data.get("password");
        const passwordConfirm = data.get("passwordConfirm");

        authContext
            .register({
                firstName,
                lastName,
                email,
                password,
                passwordConfirm
            })
            .then(() => {
                flash(6000, {
                    type: "success",
                    message: "You are now registered"
                });
                navigate("/");
            })
            .catch(errors => {
                errors.forEach(error => {
                    flash(6000, {
                        type: "error",
                        message: error.message
                    });
                });
            });
    };

    return (
        <div>
            <h1>Register</h1>
            <form
                onSubmit={handleSubmit}
                style={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center"
                }}
            >
                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        width: "100%",
                        gap: "10px"
                    }}
                >
                    <label htmlFor="firstName">first name:</label>
                    <input type="text" name="firstName" id="firstName" />
                </div>
                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        width: "100%",
                        gap: "10px"
                    }}
                >
                    <label htmlFor="lastName">last name:</label>
                    <input type="text" name="lastName" id="lastName" />
                </div>
                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        width: "100%",
                        gap: "10px"
                    }}
                >
                    <label htmlFor="email">Email:</label>
                    <input type="email" name="email" id="email" />
                </div>

                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        width: "100%",
                        gap: "10px"
                    }}
                >
                    <label htmlFor="password">Password:</label>
                    <input type="password" name="password" id="password" />
                </div>

                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        width: "100%",
                        gap: "10px"
                    }}
                >
                    <label htmlFor="passwordConfirm">Password Confirm:</label>
                    <input type="password" name="passwordConfirm" id="passwordConfirm" />
                </div>

                <button type="submit">Register</button>
            </form>
        </div>
    );
}

export default Register;

// quizz-web-app/vue-quizz-web-app/src/routes/auth/Register.vue
<template>
    <div>
        <h1>Register</h1>
        <form @submit="onSubmit">
            <div class="line">
                <label for="firstName">first name:</label>
                <input type="text" name="firstName" id="firstName" />
            </div>
            <div class="line">
                <label for="lastName">last name:</label>
                <input type="text" name="lastName" id="lastName" />
            </div>
            <div class="line">
                <label for="email">email:</label>
                <input type="email" name="email" id="email" />
            </div>
            <div class="line">
                <label for="password">password:</label>
                <input type="password" name="password" id="password" />
            </div>
            <div class="line">
                <label for="passwordConfirm">password confirm:</label>
                <input type="password" name="passwordConfirm" id="passwordConfirm" />
            </div>
            <button type="submit">Register</button>
        </form>
    </div>
</template>

<script setup>
    import { useRouter } from "vue-router";
    import { inject } from "vue";
    import { useNotification } from "@kyvg/vue3-notification";
    const { notify } = useNotification();
    const register = inject("register");
    const router = useRouter();
    const onSubmit = function (e) {
        e.preventDefault();
        const data = new FormData(e.target);
        register({
            firstName: data.get("firstName"),
            lastName: data.get("lastName"),
            email: data.get("email"),
            password: data.get("password"),
            passwordConfirm: data.get("passwordConfirm"),
        }).then(() => {
            notify({
                type: "success",
                text: "You are now registered"
            });
            router.push({ name: "Home" });
        }).catch(errors => {
            errors.forEach(error => {
                notify({
                    type: "error",
                    text: error.message
                })
            })
        })
    };
</script>

<style scoped>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .line {
        display: flex;
        align-items: center;
        justify-content: space-between;
        width: 100%;
        gap: 10px;
    }
</style>
