// quizz-web-app/react-quizz-web-app/src/routes/Quizz/Creation.jsx
import React, { useRef, useState } from "react";
import QuestionList from "../../components/Creation/QuestionList.jsx";

function Creation() {
    const titleRef = useRef();
    return (
        <div>
            <h1>Creation</h1>
            <p>
                titre du quizz: <input ref={titleRef} />
            </p>
            <QuestionList title={titleRef} />
        </div>
    );
}

export default Creation;

// quizz-web-app/vue-quizz-web-app/src/routes/Quizz/Creation.vue
<template>
    <div>
        <h1>Creation</h1>
        <p>titre du quizz: <input v-model="titleRef" /></p>
        <QuestionList :title="titleRef"></QuestionList>
    </div>
</template>

<script setup>
import QuestionList from "../../components/Creation/QuestionList.vue"
import { ref } from "vue";

const titleRef = ref('')
</script>
