// quizz-web-app/react-quizz-web-app/src/routes/Quizz/List.jsx
import { useDirectus } from "react-directus";
import { useState, useEffect } from "react";
import List from "../../components/Quizz/List.jsx";

function Quizz() {
    const { directus } = useDirectus();
    const [quizzList, setQuizzList] = useState([]);
    const [noQuizz, setNoQuizz] = useState(false);

    useEffect(() => {
        directus.items("quizz").readByQuery({ sort: ["id"], fields: ["id", "title", "owner.first_name", "owner.last_name"] }).then(response => {
            setQuizzList(response.data);
            if (response.data.length === 0) {
                setNoQuizz(true);
            }
        });
    }, []);

    return (
        <div>
            <h1>Quizz</h1>
            <List quizzList={quizzList} noQuizz={noQuizz} />
        </div>
    );
}

export default Quizz;

// quizz-web-app/vue-quizz-web-app/src/routes/Quizz/List.vue
<template>
    <div>
        <h1>Quizz</h1>
        <List :quizzList="quizzList" :isFetching="isFetching"></List>
    </div>
</template>

<script setup>
import List from "../../components/Quizz/List.vue"
import { useDirectus } from "vue-directus";
import { ref } from "vue";

const directus = useDirectus()
const isFetching = ref(true)
const quizzList = ref([])
directus.items("quizz").readByQuery({fields: ['id', "title", "ownser.first_name"]}).then(response => {
    quizzList.value = response.data
    isFetching.value =false
})
</script>
