// quizz-web-app/react-quizz-web-app/src/components/Quizz/List.jsx
import React from 'react';
import { Link } from 'react-router-dom';

function List({quizzList, noQuizz}) {
    return (
        <div>
            {noQuizz
                ? <p>
                    no quizz found: <Link to="/creation">create a new One ?</Link>
                </p>
                : <ul>
                    {quizzList.map(quizz =>
                        <li key={quizz.id}>
                            <Link to={`/quizz/${quizz.id}`} style={{
                                display: "flex",
                                justifyContent: "space-between",
                                alignItems: "center",
                                gap: "60px"
                            }}>
                                {quizz.title}
                                <span>
                                    {quizz?.owner?.first_name} {quizz?.owner?.last_name}
                                </span>
                            </Link>
                        </li>
                    )}
                </ul>}
        </div>
    );
}

export default List;

// quizz-web-app/vue-quizz-web-app/src/components/Quizz/List.vue
<template>
    <div>
        <p v-if="quizzList.length === 0 && !isFetching">no quizz found</p>
        <ul v-else>
            <li v-bind:key="quizz.id" v-for="quizz in quizzList">
                <router-link :to="`/quizz/${quizz.id}`">
                    {{ quizz.title }}
                    <span>
                        {{ quizz?.owner?.first_name }}
                        {{ quizz?.owner?.last_name }}
                    </span></router-link
                >
            </li>
        </ul>
    </div>
</template>

<script setup>
    import { defineProps } from "vue";
    const { quizzList, isFetching } = defineProps({
        quizzList: Array,
        isFetching: Boolean
    });
</script>
