// quizz-web-app/vue-quizz-web-app/src/components/Profile/MyQuizz.vue
<template>
    <h1>My Quizz</h1>
    <div class="container-quizz_list">
        <List :quizzList="quizzList" :isFetching="isFetching"></List>
    </div>
</template>

<script setup>
    import List from "../Quizz/List.vue"
    import { defineProps, ref } from "vue";
    import { useDirectus } from "vue-directus";
    const directus = useDirectus();
    const {user} = defineProps({
        user: Object
    });

    const quizzList = ref([]);
    const isFetching = ref(true)
    directus
        .items("quizz").readByQuery({
            filter: {
                owner: {
                    _eq: user.id
                }
            }
        })
        .then((response) => {
            quizzList.value = response.data;
            isFetching.value = false
        });
</script>

<style scoped>
.container-quizz_list {
    display: flex;
    justify-content: space-between;
    align-items: center;
}
</style>

// quizz-web-app/react-quizz-web-app/src/components/Profile/MyQuizz.jsx
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { useDirectus } from 'react-directus';
import List from '../Quizz/List.jsx';

function MyQuizz({user}){
    
    const { directus } = useDirectus();
    const [myQuizz, setMyQuizz] = useState([])
    useEffect(() => {
        console.log(user)
        directus.items("quizz").readByQuery(
            {
                fields: ["id", "title"],
                filter: {
                    owner: {
                        _eq: user.id
                    }
                }
            }
        ).then(response => {
            setMyQuizz(response.data);
            console.log("response.data", response.data);
        });
    }, []);
    
    return (
        <div>
            <h1>My Quizz</h1>
            <div style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
            }}>
                <List quizzList={myQuizz} />
            </div>
            <Link to="/quizz/creation">Creation</Link>
        </div>
    )
}

export default MyQuizz;
