// quizz-web-app/vue-quizz-web-app/src/components/Profile/Profile.vue
<template>
    <div>
        <h1>Profile</h1>
        <h2>Info</h2>
        <div>
            <p>First name: {{ user?.first_name }}</p>
            <p>First name: {{ user?.last_name }}</p>
            <p>First name: {{ user?.email }}</p>
            <p>First name: {{ user?.role }}</p>
        </div>
        <router-link :to="`/profile/edit/${user?.id}`">Edit</router-link>
        <MyQuizz :user="user"></MyQuizz>
    </div>
</template>

<script setup>
import MyQuizz from "./MyQuizz.vue"
import { defineProps } from 'vue';
const {user} = defineProps({
    user: Object
})
</script>

// quizz-web-app/react-quizz-web-app/src/components/Profile/Profile.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import MyQuizz from './MyQuizz.jsx';
function ProfileInfo({user}){
    return (
        <div>
            <h1>Profile</h1>
            <h2>Info</h2>
            <div>
                <p>First name: {user?.first_name}</p>
                <p>Last name: {user?.last_name}</p>
                <p>Email: {user?.email}</p>
                <p>Role: {user?.role}</p>
            </div>
            <Link to="/profile/edit/:id">Edit</Link>
            <MyQuizz user={user} />
        </div>
    );
}

export default ProfileInfo;
