// quizz-web-app/vue-quizz-web-app/src/components/Quizz/Question.vue
<template>
    <div>
        <h1>
            {{question.question}}
        </h1>
        <div class="propotition-list">
            <button v-bind:key="index" v-for="(proposition, index) in question.propositions" @click="toglePropositions" :value="index" :class="selectedPropositions.includes(index) ? 'selected' : ''">{{ proposition }}</button>
        </div>
        <button @click="validateAnswer">Valider</button>
    </div>
</template>

<script setup>
import { watch } from "vue"

const {question, selectedPropositions, toglePropositions, validateAnswer} = defineProps({
    question: Object,
    selectedPropositions: Array,
    toglePropositions: Function, 
    validateAnswer: Function
})

watch(selectedPropositions, function(){
    console.log("selectedPropositions", selectedPropositions)
})


</script>

<style scoped>
.propotition-list {
    display: grid;
    grid-template: "1fr 1fr";
    gap: 10px;
    margin-bottom: 40px;
}

.propotition-list > .selected {
    background: green;
}
</style>

// quizz-web-app/react-quizz-web-app/src/components/Quizz/Question.jsx
import React from "react";

function Question({ question, selectedPropositions, togleProposition, validateAnswer }) {
    return (
        <div>
            <h1>
                {question.question}
            </h1>
            <div
                style={{
                    display: "grid",
                    gridTemplateColumns: "1fr 1fr",
                    gridGap: "10px",
                    marginBottom: "40px"
                }}
            >
                {question.propositions.map((proposition, index) =>{
                    return <button style={{ backgroundColor: selectedPropositions.includes(index) ? "green" : "" }} key={index} onClick={togleProposition} value={index}>
                        {proposition}
                    </button>}
                )}
            </div>
            <button onClick={validateAnswer}>Valider</button>
        </div>
    );
}

export default Question;
