// quizz-web-app/react-quizz-web-app/src/layout/RightCornerLayout.jsx
import { Link } from "react-router-dom";
import { Outlet, useLocation } from "react-router-dom";
import { useAuth } from "../context/AuthContext.jsx";

function RightCornerLayout() {
    // log route name
    const location = useLocation();
    let active = location.pathname;
    const authContext = useAuth();
    const list = [["/profile/me", "Profile"], ["/", "Home"]]
    const authList = [["/login", "Login"], ["/register", "Register"], ["/logout", "Logout"]]

    if (active === "/") {
        list.splice(1, 1)
    }
    if (active === "/profile/me") {
        list.splice(0, 1)
    }
    if(!authContext.isLogin){
        list.length = 0
    }
    if (active === "/login") {
        authList.splice(0, 1)
    }
    if (active === "/register") {
        authList.splice(1, 1)
    }
    return (
        <div>
            <div
                style={{
                    position: "absolute",
                    top: 10,
                    left: 10,
                    display: "flex",
                    flexDirection: "column",
                }}
            >
                <div style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 10
                }}>
                    {list.map(function([path, name], index){
                    return (
                        <Link key={index} to={path}>
                            <label>{name}</label>
                        </Link>
                    )
                })}
                </div>
                <div style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 10
                }}>
                    {authList.map(function([path, name], index){
                    return (
                        <Link key={index} to={path}>
                            <label>{name}</label>
                        </Link>
                    )
                })}
                </div>
            </div>
            <Outlet />
        </div>
    );
}

export default RightCornerLayout;

// quizz-web-app/vue-quizz-web-app/src/layout/RightCornerLayout.vue
<template>
    <div>
        <div class="rightCorner">
            <div class="line">
                <router-link v-bind:key="name" v-for="[path, name] in list" :to="path"
                    ><label>{{ name }}</label></router-link
                >
            </div>
            <div class="line">
                <router-link v-bind:key="name" v-for="[path, name] in authList" :to="path"
                    ><label>{{ name }}</label></router-link
                >
            </div>
        </div>
        <router-view></router-view>
    </div>
</template>

<script setup>
    import { useRoute } from "vue-router";
    import { inject, watch, ref } from "vue";
    const route = useRoute();
    const defaultList = [
        ["/profile/me", "Profile"],
        ["/", "Home"]
    ];
    const defaultAuthList = [
        ["/login", "Login"],
        ["/register", "Register"],
        ["/logout", "Logout"]
    ];
    const list = ref([]);
    const authList = ref([]);
    const isLogin = inject("isLogin");

    function updateList() {
        const active = route.fullPath;
        const newList = [...defaultList];
        const newAuthList = [...defaultAuthList];
        if (active === "/") {
            newList.splice(1, 1);
        }
        if (active === "/profile/me") {
            newList.splice(0, 1);
        }
        if (!isLogin.value) {
            newList.length = 0;
        }
        if (active === "/login") {
            newAuthList.splice(0, 1);
        }
        if (active === "/register") {
            newAuthList.splice(1, 1);
        }
        list.value = newList;
        authList.value = newAuthList;
    }

    watch(route, function () {
        updateList();
    });

    updateList();
</script>

<style scoped>
    .rightCorner {
        position: absolute;
        top: 10px;
        left: 10px;
        display: flex;
        flex-direction: column;
    }

    .line {
        display: flex;
        align-items: center;
        gap: 10px;
    }
</style>
